### PR TITLE
Update 'ldap_entry' task to support new version

### PR DESCRIPTION
**Pull request by drybjed**

### CODE REVIEW

**Review by ypid — CHANGES_REQUESTED** [review]
Thanks very much. I have not quite followed the upstream discussions and decisions. In which versions is the new module included or is it included in debops-playbooks? Maybe mention that in the changelog?

**Comment by drybjed** [comment]
The new version of the `ldap_entry` module [is platted to be merged into Ansible](https://github.com/ansible/ansible-modules-extras/pull/2952) repositories. I already switched to it in the `debops-playbooks` repository, so when users update it, they will get the new version of the module.

**Comment by ypid** [comment]
Thanks, can you add the comment to the changelog?

**Review by ypid — APPROVED** [review]
Thanks!

**Pull request merged**
