### PR TITLE
Adding ability for playbook or host_vars to change nginx filename con…

### PR DESCRIPTION
**Pull request by max-b**
…fig.

Just allows upstream playbooks or host_vars to specify the nginx config filename.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/debops/ansible-owncloud/pull/5" target="_blank">ReviewNinja

**Comment by drybjed** [comment]
Change the default to 'debops.owncloud' without the owncpoud_domain and
then it will be static in regards to changing the subdomain. Otherwise,
good idea.
6 lip 2015 10:17 "max-b" notifications@github.com napisał(a):

**Comment by max-b** [comment]
So I was originally hoping to only set the property/variable if owncloud_nginx_config_filename was set up so that debops.nginx could handle it in the default manner:

https://github.com/debops/ansible-nginx/blob/master/tasks/nginx_servers.yml#L30

Unfortunately, setting it to None, "", or any other variation seemed to still cause Ansible to consider the variable "defined" and it refused to use the default in nginx_servers.yml. 

I'm wondering why use "debops.owncloud" and not just mirror the default line from nginx_servers.yml here?

**Comment by ypid** [comment]
@max-b Do you still have a need to change the filename?

**Comment by max-b** [comment]
Mmmm I haven't used this playbook in a while, so I'm not 100% sure. Also I clearly need to bring my pull request branch back into alignment with master since it's been so long. Let me take a look and I can get back to you.

**Comment by ypid** [comment]
This change should not be needed anymore with v0.3.0 which will be released shortly (filename will be static). Feel free to reopen PRs/issues for further enhancements. Thanks.

**Pull request closed without merging**
