### PR TITLE
Support MariaDB and rework.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by drybjed** [comment]
Adding MariaDB support to roles this way is the wrong approach, because right now, with Ansible dependencies, you are chaining `debops.mysql` and `debops.mariadb_server` together without benefits of `debops.mariadb` (remote database support).

The correct way to switch from `debops.mysql` to MariaDB (which also supports MySQL), is to remove the `debops.mysql` dependency with associated variables from the role, and add `debops.mariadb` (the client part, not the server part) with its own variables. This way, you get the option to setup `debops.mariadb_server` on the same host, or on different host which then can be used remotely by `debops.mariadb`.

Yes, this adds additional step for all of the applications using MariaDB/MySQL - instead of adding a host just to the `[debops_<role>]` Ansible group, you need to either add that host to `[debops_mariadb_server]` group (to install MariaDB on that host), or in the inventory, specify the MariaDB server you want to use as `mariadb_server: ''`. But now you could for example setup the database on 1 beefier host in the cluster, and point all of the application servers to it automatically.

Right now the correct way to set this all up can be found in `debops.librenms` role. The whole layout is also explained in `debops.mariadb` documentation.

**Comment by ypid** [comment]
All right. I will check that out tomorrow. Thanks for the hint.

**Comment by ypid** [comment]
I changed it now, added tags and other small things. Note that when running this on a host which was provisioned using an old version of this role it will create a new database called "owncloud" because I changed it from "www-data" to "owncloud"

**Comment by drybjed** [comment]
I just noticed that this role uses `debops.apt` as a dependency. Argh, I'm afraid I haven't used that role for too long, I would have noticed that. `debops.apt` has tons of different things and it's meant to configure APT, and not be used as a dependency - Ansible has `apt_key` and `apt_repository` modules that should be used instead of `debops.apt`.

It's the same as with `debops.users` role - you don't use it as a dependency to create user accounts for your own role, Ansible has modules for that, `group` and `user`. Roles like these are meant to be used by the user or admin through Ansible inventory, so that you don't need to create a special playbook just to create three accounts for your admins.

In other words, `debops.apt` should be dropped from this role and the APT repository should be added at the beginning of the task list. It would be interesting of upstream repository would be optional and Debian package would be installed by default - you can see this for example in `debops.docker` Althought that probably should happen on Jessie, unless `wheezy-backports` has newer ownCloud version which would be compatible with role configuration.

But there's one other thing - this PR has a lot of changes already and role isn't even tagged yet. @ypid, I would like to tag it as `v0.1.0` before making any changes, just in case anybody depends on the current setup. You could then rebase the PR on top of that. Sounds good?

**Comment by drybjed** [comment]
Also, I'm not sure about the changed database name, do you mean that the `.deb` ownCloud package creates `www-data` database?

**Comment by ypid** [comment]
Releasing `v0.1.0` before is a good idea.

About the `debops.apt` role, makes sense. I should I change that in a follow up PR or that one?

About the database name. I just think that the default current default "www-data" with no prefix is a bad example when using a remote database so I propose to change it now. The `.deb` does not create the database as it seems, at least the one from https://build.opensuse.org/.

**Comment by drybjed** [comment]
Yes, remove `debops.apt` dependency and move the APT key/package to the task list. It can be in a separate PR.

**Comment by ypid** [comment]
All right. I did it in this PR to keep it simple. I also think that it makes sense to change the default oc release to 8.1 which works nicely.

**Comment by drybjed** [comment]
Great, the previous iteration is tagged, so I hope nothing breaks when I merge this one. We'll see. :-)

**Comment by ypid** [comment]
For me it did not except the newly created database "owncloud" ;-) (which is not being used when ownCloud is already configured)

**Pull request merged**
