### PR TITLE
change 'sudo' to 'become' to fix deprecated warnings

### PR DESCRIPTION
**Pull request by cultcom**

### CODE REVIEW

**Comment by ypid** [comment]
@cultcom Hey, I would be interested how you automated this :wink:

Please note that such DebOps wide replacements should be discussed first.

**Comment by ypid** [comment]
https://docs.travis-ci.com/user/ci-environment/

**Comment by cultcom** [comment]
@ypid: there are two options I found for automation:
1. git-hub package on ubuntu/mint
a python script which initializes an API key and uses it for such things
2. https://github.com/github/hub
a kind of official binary warping arround "git" to add github subcommands.

And yes, I am stupid and did not read the travis docs beforehand, sorry for that, I revert the changes on those files and try it again tomorrow.
That will reduce the involved repositories a lot.

**Comment by ypid** [comment]
> And yes, I am stupid and did not read the travis docs beforehand, sorry for that, I revert the changes on those files and try it again tomorrow.
> That will reduce the involved repositories a lot.

Can you please talk with us before you do that? Either on IRC or in this PR. We review all patches and then merge them locally. Check: https://docs.debops.org/en/latest/debops-policy/docs/code-signing-policy.html
So doing this causes a certain overhead.

I take the approach to run a few rewrite rules using [sphinx-optimize](https://github.com/ypid/ypid-ansible-common/blob/master/bin/sphinx-optimize) against the repositories when I fix typos or so on anyway.

Believe me, I sometimes would like to achieve a similar thing then you did with your patch series. Just automatically fix an issue and then automatically open PR for each repo. For the one who is doing that it does not matter if there are 100 or 1000 repos but for the maintainers on the other side it does matter. Also, we could do such global operations more easily anyway. But our current workflow is not yet setup for doing something like this also because we review all changes before they enter the main repos.

Related to: https://github.com/debops/debops-tools/issues/128
Related to: https://github.com/debops/debops-tools/issues/120
Related to: https://github.com/debops/debops-tools/pull/163

> there are two options I found for automation:

And how did you do your first patch series? Manually? :smile: Remember that we are an automation project :wink:

**Comment by cultcom** [comment]
@ypid: semi manually, I grep'ed for sudo: and sudo_user: and checked all the results manually before I changed the occasions by sed and vim depending on the file.
The travis files were a severe misunderstanding...

**Comment by ypid** [comment]
And the forking of the repos on github and opening the PRs :wink: ?

**Comment by cultcom** [comment]
@ypid: yes, that is where I used the "git-hub" script. Just a bash "for" loop and "git-hub clone" and it forks the upstream to your own account. It can also automatically create PRs for you using the official  github API. Very handsome.

**Pull request closed without merging**
